# Multiple Stock Data for Python Using Yahoo Finance API

!pip3 install yfinance

Note: Using the Public API (without authentication), you are limited to 2,000 requests per hour per IP (or up to a total of 48,000 requests a day).

In [1]:
import yfinance as yf
import pandas as pd

## Get Historical Market Data

Data to be used for the simulations in the [Build A Killer Stock Portfolio Using Python](https://www.youtube.com/watch?v=bvDkel5whUY) of channel [Computer Science](https://www.youtube.com/channel/UCbmb5IoBtHZTpYZCDBOC1CA).

Ticks were captured from the video

In [2]:
ticks_list = [
    "ATVI", "ADBE", "AMD", "ALXN", "ALGN", "GOOGL", "GOOG", "AMZN", "AEP", "AMGN", "ADI",
    "ANSS", "AAPL", "AMAT", "ASML", "TEAM", "ADSK", "ADP", "BIDU", "BIIB", "BKNG", "AVGO", "CDNS", "CDW",
    "CERN", "CHTR", "CHKP", "CTAS", "CSCO", "CTSH", "CMCSA", "CPRT", "COST", "CSX", "DXCM", "DOCU", "DLTR",
    "EBAY", "EA", "EXC", "FB", "FAST", "FISV", "FOXA", "FOX", "GILD", "IDXX", "ILMN", "INCY", "INTC", "INTU",
    "ISRG", "JD", "KDP", "KLAC", "KHC", "LRCX", "LULU", "MAR", "MRVL", "MTCH", "MXIM", "MELI", "MCHP", "MU",
    "MSFT", "MRNA", "MDLZ", "MNST", "NTES", "NFLX", "NVDA", "NXPI", "ORLY", "OKTA", "PCAR", "PAYX", "PYPL",
    "PTON", "PEP", "PDD", "QCOM", "REGN", "ROST", "SGEN", "SIRI", "SWKS", "SPLK", "SBUX", "SNPS", "TMUS",
    "TSLA", "TXN", "TCOM", "VRSN", "VRSK", "VRTX", "WBA", "WDAY", "XEL", "XLNX", "ZM"
]

Get the closing price for the last 5 years for each tick.

In [3]:
stock_data = []
for tick in ticks_list:
    ticker = yf.Ticker(tick)
    hist_tick = ticker.history(period="5y")
    if 'Close' in hist_tick.columns:
        stock_tick = hist_tick[['Close']].copy()
        stock_tick.rename(columns={'Close': tick}, inplace=True)
        stock_data.append(stock_tick)

Generate dataset where each date has values

In [4]:
price_data_inner = pd.concat(stock_data, axis=1, join='inner')

In [5]:
price_data_inner

,ATVI,ADBE,AMD,ALXN,ALGN,GOOGL,GOOG,AMZN,AEP,AMGN,...,TXN,TCOM,VRSN,VRSK,VRTX,WBA,WDAY,XEL,XLNX,ZM
Date,,,,,,,,,,,,,,,,,,,,,
2019-09-26,53.865734,283.809998,29.469999,98.699997,178.990005,1242.290039,1241.390015,1739.839966,90.607765,188.869873,...,123.516968,29.809999,191.190002,158.016418,169.550003,51.409519,174.440002,63.479950,95.403000,79.750000
2019-09-27,51.988087,277.540009,28.719999,97.769997,175.839996,1225.949951,1225.089966,1725.449951,90.521271,188.444534,...,122.581741,29.020000,187.250000,154.346024,166.740005,51.723213,168.649994,63.276646,94.137360,76.040001
2019-09-30,52.574226,276.250000,28.990000,97.940002,180.919998,1221.140015,1219.000000,1735.910034,90.031189,187.062164,...,124.606468,29.290001,188.630005,156.875626,169.419998,52.578777,169.960007,62.821632,94.088318,76.199997
2019-10-01,52.554359,272.709991,28.760000,97.790001,182.300003,1206.000000,1205.099976,1735.650024,89.579544,186.752838,...,123.979759,29.840000,183.949997,155.199142,167.580002,51.998901,168.740005,62.879704,90.301231,75.809998
2019-10-02,51.908607,266.660004,28.309999,97.480003,179.750000,1177.920044,1176.630005,1713.229980,88.532112,182.905472,...,122.292503,29.940001,177.949997,152.104080,166.710007,50.221241,165.809998,61.321030,90.703484,73.849998
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-01-20,95.120003,469.730011,88.750000,157.740005,564.369995,1880.069946,1886.900024,3263.379883,80.750000,252.360001,...,173.330002,34.580002,199.940002,194.710007,236.699997,48.090000,226.789993,65.430000,138.000000,382.799988
2021-01-21,94.599998,472.019989,91.529999,157.860001,543.809998,1884.150024,1891.250000,3306.989990,80.970001,252.029999,...,175.100006,33.689999,197.139999,194.869995,238.639999,47.070000,229.389999,65.110001,141.160004,382.809998
2021-01-22,94.430000,472.440002,92.790001,159.729996,534.080017,1892.560059,1901.050049,3292.229980,82.080002,253.500000,...,172.809998,33.580002,194.750000,192.759995,237.589996,47.450001,235.529999,64.760002,142.940002,383.399994
2021-01-25,93.400002,473.440002,94.129997,161.320007,539.469971,1894.280029,1899.400024,3294.000000,82.589996,257.100006,...,172.919998,32.779999,192.000000,188.679993,241.309998,47.820000,234.990005,66.500000,145.139999,391.829987
2021-01-26,92.669998,475.850006,94.680000,162.214996,537.750000,1904.979980,1914.300049,3325.709961,81.839996,257.606812,...,172.509995,31.885000,195.210007,189.539993,238.339996,48.674999,234.500000,65.737297,144.899994,380.135010

In [6]:
price_data_inner.to_csv('NYSE_close_inner.csv')

Prepare data to be used for simulations in the [Build A Killer Stock Portfolio Using Python]

In [7]:
price_data_outer = pd.concat(stock_data, axis=1, join='outer')

In [8]:
price_data_outer

,ATVI,ADBE,AMD,ALXN,ALGN,GOOGL,GOOG,AMZN,AEP,AMGN,...,TXN,TCOM,VRSN,VRSK,VRTX,WBA,WDAY,XEL,XLNX,ZM
Date,,,,,,,,,,,,,,,,,,,,,
2016-01-26,34.123150,86.889999,2.070000,152.639999,62.209999,733.789978,713.039978,601.250000,49.089256,133.714706,...,44.352009,42.830002,75.150002,70.259438,92.199997,69.336983,66.650002,31.649551,43.874077,NaN
2016-01-27,32.934155,84.849998,2.130000,151.119995,61.419998,717.580017,699.989990,583.349976,49.080822,130.836594,...,44.325752,41.570000,74.739998,69.904190,92.500000,68.472908,64.500000,31.572084,43.683514,NaN
2016-01-28,32.663490,84.519997,2.080000,145.610001,59.509998,748.299988,730.960022,635.349976,50.143581,128.993179,...,45.066147,40.840000,77.080002,70.269310,92.760002,67.739716,62.029999,32.338146,43.556480,NaN
2016-01-29,33.659153,89.129997,2.200000,145.929993,66.139999,761.349976,742.950012,587.000000,51.425636,132.801651,...,46.652664,42.680000,75.599998,72.035675,90.750000,69.581398,63.009998,32.897621,45.616337,NaN
2016-02-01,33.514153,89.610001,2.140000,143.500000,67.550003,770.770020,752.000000,574.809998,52.117279,132.819077,...,46.564533,41.970001,75.650002,71.157425,92.389999,69.886864,64.839996,33.190277,45.280594,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-01-20,95.120003,469.730011,88.750000,157.740005,564.369995,1880.069946,1886.900024,3263.379883,80.750000,252.360001,...,173.330002,34.580002,199.940002,194.710007,236.699997,48.090000,226.789993,65.430000,138.000000,382.799988
2021-01-21,94.599998,472.019989,91.529999,157.860001,543.809998,1884.150024,1891.250000,3306.989990,80.970001,252.029999,...,175.100006,33.689999,197.139999,194.869995,238.639999,47.070000,229.389999,65.110001,141.160004,382.809998
2021-01-22,94.430000,472.440002,92.790001,159.729996,534.080017,1892.560059,1901.050049,3292.229980,82.080002,253.500000,...,172.809998,33.580002,194.750000,192.759995,237.589996,47.450001,235.529999,64.760002,142.940002,383.399994
2021-01-25,93.400002,473.440002,94.129997,161.320007,539.469971,1894.280029,1899.400024,3294.000000,82.589996,257.100006,...,172.919998,32.779999,192.000000,188.679993,241.309998,47.820000,234.990005,66.500000,145.139999,391.829987
2021-01-26,92.669998,475.850006,94.680000,162.214996,537.750000,1904.979980,1914.300049,3325.709961,81.839996,257.606812,...,172.509995,31.885000,195.210007,189.539993,238.339996,48.674999,234.500000,65.737297,144.899994,380.135010

In [9]:
price_data_outer.to_csv('NYSE_close_outer.csv')

Note: If complete dataset for the perion "2016-01-26" to "2021-01-26" is required, then the ticks "DOCU", "FOXA", "FOX", "MRNA", "OKTA", "PTON", "PDD" and "ZM" should be removed.