# Determine If A Stock Is Under/Over Valued

Based on [Determine If A Stock Is Under/Over Valued Using Python Programming](https://www.youtube.com/watch?v=kpK1aXnPrgM) from [Computer Science](https://www.youtube.com/channel/UCbmb5IoBtHZTpYZCDBOC1CA)

**Disclaimer:** _Investing in the stock market involves risk and can lead to monetary loss. This material is purely for educational purposes and should not be taken as professional investment advice. Invest at your own discretion._

In [1]:
import pandas as pd
import numpy as np

Store the data **GOOG data added manually**

In [2]:
df = pd.read_csv('InformationTechnologyStocks.csv')

Show data

In [3]:
df

   Tickers  PE_Ratio  Current_Price  Earnings_Per_Share
0     AMZN     57.57        3303.50           57.380000
1     AAPL     29.19         148.89            5.100000
2     GOOG     29.34        2767.79           93.074644
3     MSFT     36.00         289.81            8.050000
4     NFLX     52.92         510.72            9.650000
5        V     46.83         231.79            4.950000
6     PYPL     66.97         274.59            4.100000
7       MA     50.27         361.98            7.200000
8     ADBE     54.87         634.35           11.560000
9     INTC     11.92          53.54            4.490000
10     CRM     52.40         248.39            4.740000
11    AVGO     45.01         484.26           10.760000
12     ACN     35.99         321.76            8.940000
13     TXN     26.20         187.87            7.170000
14    QCOM     18.37         147.15            8.010000
15    ORCL     19.74          89.81            4.550000
16    INTU     68.05         536.92            7.890000
17    AMAT     26.92         129.22            4.800000
18     AMD     37.50         106.50            2.840000
19     NOW    693.34         581.57            0.838800
20      SQ    244.17         268.59            1.100000
21      MU     19.41          70.25            3.620000
22      FB     26.90         362.65           13.480000
23    LRCX     24.67         583.51           23.650000
24     ADP     35.40         214.90            6.070000

Set tickers as index

In [4]:
df = df.set_index('Tickers')

Show data

In [5]:
df

         PE_Ratio  Current_Price  Earnings_Per_Share
Tickers
AMZN        57.57        3303.50           57.380000
AAPL        29.19         148.89            5.100000
GOOG        29.34        2767.79           93.074644
MSFT        36.00         289.81            8.050000
NFLX        52.92         510.72            9.650000
V           46.83         231.79            4.950000
PYPL        66.97         274.59            4.100000
MA          50.27         361.98            7.200000
ADBE        54.87         634.35           11.560000
INTC        11.92          53.54            4.490000
CRM         52.40         248.39            4.740000
AVGO        45.01         484.26           10.760000
ACN         35.99         321.76            8.940000
TXN         26.20         187.87            7.170000
QCOM        18.37         147.15            8.010000
ORCL        19.74          89.81            4.550000
INTU        68.05         536.92            7.890000
AMAT        26.92         129.22            4.800000
AMD         37.50         106.50            2.840000
NOW        693.34         581.57            0.838800
SQ         244.17         268.59            1.100000
MU          19.41          70.25            3.620000
FB          26.90         362.65           13.480000
LRCX        24.67         583.51           23.650000
ADP         35.40         214.90            6.070000

Calculate and show the mean P/E ratio

In [6]:
PE_Ratio_Mean = df.PE_Ratio.mean()

In [7]:
PE_Ratio_Mean

72.39800000000001

Calculate and show the Fair Market Value

In [8]:
df['Fair_Market_Value'] = PE_Ratio_Mean * df['Earnings_Per_Share']

Show the data

In [9]:
df

         PE_Ratio  Current_Price  Earnings_Per_Share  Fair_Market_Value
Tickers
AMZN        57.57        3303.50           57.380000        4154.197240
AAPL        29.19         148.89            5.100000         369.229800
GOOG        29.34        2767.79           93.074644        6738.418076
MSFT        36.00         289.81            8.050000         582.803900
NFLX        52.92         510.72            9.650000         698.640700
V           46.83         231.79            4.950000         358.370100
PYPL        66.97         274.59            4.100000         296.831800
MA          50.27         361.98            7.200000         521.265600
ADBE        54.87         634.35           11.560000         836.920880
INTC        11.92          53.54            4.490000         325.067020
CRM         52.40         248.39            4.740000         343.166520
AVGO        45.01         484.26           10.760000         779.002480
ACN         35.99         321.76            8.940000         647.238120
TXN         26.20         187.87            7.170000         519.093660
QCOM        18.37         147.15            8.010000         579.907980
ORCL        19.74          89.81            4.550000         329.410900
INTU        68.05         536.92            7.890000         571.220220
AMAT        26.92         129.22            4.800000         347.510400
AMD         37.50         106.50            2.840000         205.610320
NOW        693.34         581.57            0.838800          60.727442
SQ         244.17         268.59            1.100000          79.637800
MU          19.41          70.25            3.620000         262.080760
FB          26.90         362.65           13.480000         975.925040
LRCX        24.67         583.51           23.650000        1712.212700
ADP         35.40         214.90            6.070000         439.455860

Calculate and show a companies value ratio to determine if that company is over valued or under valued

In [10]:
df['Over_Under_Ratio'] = df['Current_Price'] / df['Fair_Market_Value']

Show the data

In [11]:
df

,PE_Ratio,Current_Price,Earnings_Per_Share,Fair_Market_Value,Over_Under_Ratio
Tickers,,,,,
AMZN,57.57,3303.50,57.380000,4154.197240,0.795220
AAPL,29.19,148.89,5.100000,369.229800,0.403245
GOOG,29.34,2767.79,93.074644,6738.418076,0.410748
MSFT,36.00,289.81,8.050000,582.803900,0.497268
NFLX,52.92,510.72,9.650000,698.640700,0.731020
V,46.83,231.79,4.950000,358.370100,0.646789
PYPL,66.97,274.59,4.100000,296.831800,0.925069
MA,50.27,361.98,7.200000,521.265600,0.694425
ADBE,54.87,634.35,11.560000,836.920880,0.757957
INTC,11.92,53.54,4.490000,325.067020,0.164704
CRM,52.40,248.39,4.740000,343.166520,0.723818
AVGO,45.01,484.26,10.760000,779.002480,0.621641
ACN,35.99,321.76,8.940000,647.238120,0.497128
TXN,26.20,187.87,7.170000,519.093660,0.361919
QCOM,18.37,147.15,8.010000,579.907980,0.253747
ORCL,19.74,89.81,4.550000,329.410900,0.272638
INTU,68.05,536.92,7.890000,571.220220,0.939953
AMAT,26.92,129.22,4.800000,347.510400,0.371845
AMD,37.50,106.50,2.840000,205.610320,0.517970
NOW,693.34,581.57,0.838800,60.727442,9.576725
SQ,244.17,268.59,1.100000,79.637800,3.372645
MU,19.41,70.25,3.620000,262.080760,0.268047
FB,26.90,362.65,13.480000,975.925040,0.371596
LRCX,24.67,583.51,23.650000,1712.212700,0.340793
ADP,35.40,214.90,6.070000,439.455860,0.489014

Create a new column to store and show a label of under valued and over valued stocks

In [12]:
df['Value_Label'] = np.where(df['Over_Under_Ratio'] < 1.0, 'Under Valued', 'Fair or Over Valued')

Show the data

In [13]:
df

,PE_Ratio,Current_Price,Earnings_Per_Share,Fair_Market_Value,Over_Under_Ratio,Value_Label
Tickers,,,,,,
AMZN,57.57,3303.50,57.380000,4154.197240,0.795220,Under Valued
AAPL,29.19,148.89,5.100000,369.229800,0.403245,Under Valued
GOOG,29.34,2767.79,93.074644,6738.418076,0.410748,Under Valued
MSFT,36.00,289.81,8.050000,582.803900,0.497268,Under Valued
NFLX,52.92,510.72,9.650000,698.640700,0.731020,Under Valued
V,46.83,231.79,4.950000,358.370100,0.646789,Under Valued
PYPL,66.97,274.59,4.100000,296.831800,0.925069,Under Valued
MA,50.27,361.98,7.200000,521.265600,0.694425,Under Valued
ADBE,54.87,634.35,11.560000,836.920880,0.757957,Under Valued
INTC,11.92,53.54,4.490000,325.067020,0.164704,Under Valued
CRM,52.40,248.39,4.740000,343.166520,0.723818,Under Valued
AVGO,45.01,484.26,10.760000,779.002480,0.621641,Under Valued
ACN,35.99,321.76,8.940000,647.238120,0.497128,Under Valued
TXN,26.20,187.87,7.170000,519.093660,0.361919,Under Valued
QCOM,18.37,147.15,8.010000,579.907980,0.253747,Under Valued
ORCL,19.74,89.81,4.550000,329.410900,0.272638,Under Valued
INTU,68.05,536.92,7.890000,571.220220,0.939953,Under Valued
AMAT,26.92,129.22,4.800000,347.510400,0.371845,Under Valued
AMD,37.50,106.50,2.840000,205.610320,0.517970,Under Valued
NOW,693.34,581.57,0.838800,60.727442,9.576725,Fair or Over Valued
SQ,244.17,268.59,1.100000,79.637800,3.372645,Fair or Over Valued
MU,19.41,70.25,3.620000,262.080760,0.268047,Under Valued
FB,26.90,362.65,13.480000,975.925040,0.371596,Under Valued
LRCX,24.67,583.51,23.650000,1712.212700,0.340793,Under Valued
ADP,35.40,214.90,6.070000,439.455860,0.489014,Under Valued

Show the percentage that the stock is over or under valued

In [14]:
df['Value_Percentage'] = abs(df['Over_Under_Ratio'] - 1) * 100

Show the data

In [15]:
df

,PE_Ratio,Current_Price,Earnings_Per_Share,Fair_Market_Value,Over_Under_Ratio,Value_Label,Value_Percentage
Tickers,,,,,,,
AMZN,57.57,3303.50,57.380000,4154.197240,0.795220,Under Valued,20.478018
AAPL,29.19,148.89,5.100000,369.229800,0.403245,Under Valued,59.675519
GOOG,29.34,2767.79,93.074644,6738.418076,0.410748,Under Valued,58.925226
MSFT,36.00,289.81,8.050000,582.803900,0.497268,Under Valued,50.273154
NFLX,52.92,510.72,9.650000,698.640700,0.731020,Under Valued,26.898046
V,46.83,231.79,4.950000,358.370100,0.646789,Under Valued,35.321055
PYPL,66.97,274.59,4.100000,296.831800,0.925069,Under Valued,7.493065
MA,50.27,361.98,7.200000,521.265600,0.694425,Under Valued,30.557474
ADBE,54.87,634.35,11.560000,836.920880,0.757957,Under Valued,24.204305
INTC,11.92,53.54,4.490000,325.067020,0.164704,Under Valued,83.529550
CRM,52.40,248.39,4.740000,343.166520,0.723818,Under Valued,27.618230
AVGO,45.01,484.26,10.760000,779.002480,0.621641,Under Valued,37.835885
ACN,35.99,321.76,8.940000,647.238120,0.497128,Under Valued,50.287230
TXN,26.20,187.87,7.170000,519.093660,0.361919,Under Valued,63.808073
QCOM,18.37,147.15,8.010000,579.907980,0.253747,Under Valued,74.625285
ORCL,19.74,89.81,4.550000,329.410900,0.272638,Under Valued,72.736178
INTU,68.05,536.92,7.890000,571.220220,0.939953,Under Valued,6.004728
AMAT,26.92,129.22,4.800000,347.510400,0.371845,Under Valued,62.815501
AMD,37.50,106.50,2.840000,205.610320,0.517970,Under Valued,48.202989
NOW,693.34,581.57,0.838800,60.727442,9.576725,Fair or Over Valued,857.672474
SQ,244.17,268.59,1.100000,79.637800,3.372645,Fair or Over Valued,237.264465
MU,19.41,70.25,3.620000,262.080760,0.268047,Under Valued,73.195285
FB,26.90,362.65,13.480000,975.925040,0.371596,Under Valued,62.840384
LRCX,24.67,583.51,23.650000,1712.212700,0.340793,Under Valued,65.920706
ADP,35.40,214.90,6.070000,439.455860,0.489014,Under Valued,51.098615

Show only a list of stocks that are considered under valued

In [16]:
df[df.Value_Label == 'Under Valued'].index

Index(['AMZN', 'AAPL', 'GOOG', 'MSFT', 'NFLX', 'V', 'PYPL', 'MA', 'ADBE',
       'INTC', 'CRM', 'AVGO', 'ACN', 'TXN', 'QCOM', 'ORCL', 'INTU', 'AMAT',
       'AMD', 'MU', 'FB', 'LRCX', 'ADP'],
      dtype='object', name='Tickers')

**THIS IS NOT AN INVESTMENT ADVICE!**